ahbsd.lib.NamedCollections.DictionaryOfNamedCollection< K, V > Class Template Reference
Default implementation of IDictionaryOfNamedCollections<K, V>.
Public Member Functions
void Add (K key, string name)
Adds a new key with the name of the new INamedCollection<T>.
void Add (K key, V value, string name=null)
Adds a value to the INamedCollection<T> of key.
void Add (KeyValuePair< K, V > keyValuePair, string name=null)
Adds a KeyValuePair<TKey, TValue>.
Events
EventHandler< EventArgs< INamedCollection< V > > > OnNamedCollectionAdded
Happenes if a new INamedCollection<T> was added.
Detailed Description
Default implementation of IDictionaryOfNamedCollections<K, V>.
Template Parameters
K Key Type.
V Value Type of the INamedCollection<T>.
Member Function Documentation
Add() [1/3]
void ahbsd.lib.NamedCollections.DictionaryOfNamedCollection< K, V >.Add (K key, string name)
Adds a new key with the name of the new INamedCollection<T>.
Parameters
key The new key.
name The name of the new INamedCollection<T>.
Exceptions
ArgumentException If key already exists.
Implements ahbsd.lib.NamedCollections.IDictionaryOfNamedCollections< K, V >.
References ahbsd.lib.NamedCollections.DictionaryOfNamedCollection< K, V >.OnNamedCollectionAdded.
Referenced by ahbsd.lib.NamedCollections.DictionaryOfNamedCollection< K, V >.Add().
Add() [2/3]
void ahbsd.lib.NamedCollections.DictionaryOfNamedCollection< K, V >.Add (K key, V value, string name = null)
Adds a value to the INamedCollection<T> of key.
Parameters
key The Key.
value The Value.
name The name of the new INamedCollection<T>.
If the key already exists the name isn't needed; if the key doesn't exists a name is needed, otherwise a KeyNotFoundException will be thrown.
Exceptions
KeyNotFoundException If the key isn't there AND a name for the new INamedCollection<T> was missing.
Implements ahbsd.lib.NamedCollections.IDictionaryOfNamedCollections< K, V >.
References ahbsd.lib.NamedCollections.DictionaryOfNamedCollection< K, V >.Add(), and ahbsd.lib.NamedCollections.DictionaryOfNamedCollection< K, V >.OnNamedCollectionAdded.
Add() [3/3]
void ahbsd.lib.NamedCollections.DictionaryOfNamedCollection< K, V >.Add (KeyValuePair< K, V > keyValuePair, string name = null)
Adds a KeyValuePair<TKey, TValue>.
Parameters
keyValuePair The KeyValuePair<TKey, TValue>.
name The name of the new INamedCollection<T>.
If the key already exists the name isn't needed; if the key doesn't exists a name is needed, otherwise a KeyNotFoundException will be thrown.
Exceptions
KeyNotFoundException If the key isn't there AND a name for the new INamedCollection<T> was missing.
Implements ahbsd.lib.NamedCollections.IDictionaryOfNamedCollections< K, V >.
References ahbsd.lib.NamedCollections.DictionaryOfNamedCollection< K, V >.Add().
Event Documentation
OnNamedCollectionAdded
EventHandler<EventArgs<INamedCollection<V> > > ahbsd.lib.NamedCollections.DictionaryOfNamedCollection< K, V >.OnNamedCollectionAdded
Happenes if a new INamedCollection<T> was added.
Referenced by ahbsd.lib.NamedCollections.DictionaryOfNamedCollection< K, V >.Add().
The documentation for this class was generated from the following file:
ahbsd.lib/NamedCollections/DictionaryOfNamedCollection.cs