ahbsd.lib.Password.CharacteristicDictionary Class Reference
Characteristic Dictionarry.
Public Member Functions
CharacteristicDictionary ()
Constructor without parameter.
CharacteristicDictionary (IContainer container)
Constructor with a given owning container.
void Add (Charasteristic key, bool value)
Throws an Exception.
void Add (KeyValuePair< Charasteristic, bool > item)
Throws an Exception.
void Clear ()
Re-Initialize the object.
bool Contains (KeyValuePair< Charasteristic, bool > item)
bool ContainsKey (Charasteristic key)
void CopyTo (KeyValuePair< Charasteristic, bool >[] array, int arrayIndex)
IEnumerator< KeyValuePair< Charasteristic, bool > > GetEnumerator ()
bool Remove (Charasteristic key)
bool Remove (KeyValuePair< Charasteristic, bool > item)
bool TryGetValue (Charasteristic key, [MaybeNullWhen(false)] out bool value)
override string ToString ()
Gets a short info of the characteristic.
Package Functions
CharacteristicDictionary (string value)
Constructor with a given password.
CharacteristicDictionary (IPassword value)
Constructor with a given password.
CharacteristicDictionary (string value, IContainer container)
Constructor with a given password and a given owning container.
CharacteristicDictionary (IPassword value, IContainer container)
Constructor with a given password and a given owning container.
Properties
bool this[Charasteristic key] [get, set]
Gets or sets the value of the given key.
ICollection< Charasteristic > Keys [get]
Gets the Keys.
ICollection< bool > Values [get]
Gets all values.
int Count [get]
Gets the amount of KeyValuePair<TKey, TValue>s (5).
bool IsReadOnly [get]
Gets the readability.
string Name [get]
Gets the name of this component.
Detailed Description
Characteristic Dictionarry.
Constructor & Destructor Documentation
CharacteristicDictionary() [1/6]
ahbsd.lib.Password.CharacteristicDictionary.CharacteristicDictionary ()
Constructor without parameter.
CharacteristicDictionary() [2/6]
ahbsd.lib.Password.CharacteristicDictionary.CharacteristicDictionary (string value) [package]
Constructor with a given password.
Parameters
value The given password.
References ahbsd.lib.Password.CharacteristicDictionary.ToString().
CharacteristicDictionary() [3/6]
ahbsd.lib.Password.CharacteristicDictionary.CharacteristicDictionary (IPassword value) [package]
Constructor with a given password.
Parameters
value The given password.
References ahbsd.lib.Password.CharacteristicDictionary.ToString().
CharacteristicDictionary() [4/6]
ahbsd.lib.Password.CharacteristicDictionary.CharacteristicDictionary (IContainer container)
Constructor with a given owning container.
Parameters
container The given owning container.
CharacteristicDictionary() [5/6]
ahbsd.lib.Password.CharacteristicDictionary.CharacteristicDictionary (string value, IContainer container) [package]
Constructor with a given password and a given owning container.
Parameters
value The given password.
container The given owning container.
References ahbsd.lib.Password.CharacteristicDictionary.ToString().
CharacteristicDictionary() [6/6]
ahbsd.lib.Password.CharacteristicDictionary.CharacteristicDictionary (IPassword value, IContainer container) [package]
Constructor with a given password and a given owning container.
Parameters
value The given password.
container The given owning container.
References ahbsd.lib.Password.CharacteristicDictionary.ToString().
Member Function Documentation
Add() [1/2]
void ahbsd.lib.Password.CharacteristicDictionary.Add (Charasteristic key, bool value)
Throws an Exception.
Exceptions
Exception Allways, since no add is possible here.
Add() [2/2]
void ahbsd.lib.Password.CharacteristicDictionary.Add (KeyValuePair< Charasteristic, bool > item)
Throws an Exception.
Exceptions
Exception Allways, since no add is possible here.
Clear()
void ahbsd.lib.Password.CharacteristicDictionary.Clear ()
Re-Initialize the object.
Contains()
bool ahbsd.lib.Password.CharacteristicDictionary.Contains (KeyValuePair< Charasteristic, bool > item)
Parameters
item
Returns
ContainsKey()
bool ahbsd.lib.Password.CharacteristicDictionary.ContainsKey (Charasteristic key)
Parameters
key
Returns
CopyTo()
void ahbsd.lib.Password.CharacteristicDictionary.CopyTo (KeyValuePair< Charasteristic, bool >[] array, int arrayIndex)
Parameters
array
arrayIndex
GetEnumerator()
IEnumerator<KeyValuePair<Charasteristic, bool> > ahbsd.lib.Password.CharacteristicDictionary.GetEnumerator ()
Returns
Remove() [1/2]
bool ahbsd.lib.Password.CharacteristicDictionary.Remove (Charasteristic key)
Parameters
key
Returns
Remove() [2/2]
bool ahbsd.lib.Password.CharacteristicDictionary.Remove (KeyValuePair< Charasteristic, bool > item)
Parameters
item
Returns
ToString()
override string ahbsd.lib.Password.CharacteristicDictionary.ToString ()
Gets a short info of the characteristic.
Returns
A short info of the characteristic.
Implements ahbsd.lib.Password.ICharacteristicDictionary.
Referenced by ahbsd.lib.Password.CharacteristicDictionary.CharacteristicDictionary().
TryGetValue()
bool ahbsd.lib.Password.CharacteristicDictionary.TryGetValue (Charasteristic key, [MaybeNullWhen(false)] out bool value)
Parameters
key
value
Returns
Property Documentation
Count
int ahbsd.lib.Password.CharacteristicDictionary.Count [get]
Gets the amount of KeyValuePair<TKey, TValue>s (5).
The amount of KeyValuePair<TKey, TValue>s.
IsReadOnly
bool ahbsd.lib.Password.CharacteristicDictionary.IsReadOnly [get]
Gets the readability.
true if readonly, otherwise false.
Keys
ICollection<Charasteristic> ahbsd.lib.Password.CharacteristicDictionary.Keys [get]
Gets the Keys.
The Keys.
Each available Charasteristic.
Name
string ahbsd.lib.Password.CharacteristicDictionary.Name [get]
Gets the name of this component.
The name of this component.
this[Charasteristic key]
bool ahbsd.lib.Password.CharacteristicDictionary.this[Charasteristic key] [get], [set]
Gets or sets the value of the given key.
Parameters
key The given key.
Returns
The value of the given key.
Values
ICollection<bool> ahbsd.lib.Password.CharacteristicDictionary.Values [get]
Gets all values.
The values.
The documentation for this class was generated from the following file:
ahbsd.lib/Password/CharacteristicDictionary.cs