ahbsd.lib.NamedCollections.DictionaryOfNamedList< K, V > Class Template Reference
Default implementation of IDictionaryOfNamedList<K, V>.
Public Member Functions
void Add (K key, string name)
Adds a key.
void Add (K key, V value, string name=null)
Adds a value to the INamedList<T> of key.
void Add (KeyValuePair< K, V > keyValuePair, string name=null)
Adds a KeyValuePair<TKey, TValue>.
Events
EventHandler< EventArgs< INamedList< V > > > OnNamedListAdded
Happenes, if a new INamedList<T> was added.
Detailed Description
Default implementation of IDictionaryOfNamedList<K, V>.
Template Parameters
K The type of the key.
V The type of the INamedList<T>-ValueType.
Member Function Documentation
Add() [1/3]
void ahbsd.lib.NamedCollections.DictionaryOfNamedList< K, V >.Add (K key, string name)
Adds a key.
Parameters
key The key.
name The name of the new INamedList<T>.
Exceptions
ArgumentException If key already exists.
Implements ahbsd.lib.NamedCollections.IDictionaryOfNamedList< K, V >.
References ahbsd.lib.NamedCollections.DictionaryOfNamedList< K, V >.OnNamedListAdded.
Referenced by ahbsd.lib.NamedCollections.DictionaryOfNamedList< K, V >.Add().
Add() [2/3]
void ahbsd.lib.NamedCollections.DictionaryOfNamedList< K, V >.Add (K key, V value, string name = null)
Adds a value to the INamedList<T> of key.
Parameters
key The key.
value The value.
name The name of the new INamedList<T>.
If the key already exists the name isn't needed; if the key doesn't exists a name is needed, otherwise a KeyNotFoundException will be thrown.
Exceptions
KeyNotFoundException If the key isn't there AND a name for the new INamedList<T> was missing.
Implements ahbsd.lib.NamedCollections.IDictionaryOfNamedList< K, V >.
References ahbsd.lib.NamedCollections.DictionaryOfNamedList< K, V >.Add(), and ahbsd.lib.NamedCollections.DictionaryOfNamedList< K, V >.OnNamedListAdded.
Add() [3/3]
void ahbsd.lib.NamedCollections.DictionaryOfNamedList< K, V >.Add (KeyValuePair< K, V > keyValuePair, string name = null)
Adds a KeyValuePair<TKey, TValue>.
Parameters
keyValuePair The KeyValuePair<TKey, TValue>.
name The name of the new INamedList<T>.
If the key already exists the name isn't needed; if the key doesn't exists a name is needed, otherwise a KeyNotFoundException will be thrown.
Exceptions
KeyNotFoundException If the key isn't there AND a name for the new INamedList<T> was missing.
Implements ahbsd.lib.NamedCollections.IDictionaryOfNamedList< K, V >.
References ahbsd.lib.NamedCollections.DictionaryOfNamedList< K, V >.Add().
Event Documentation
OnNamedListAdded
EventHandler<EventArgs<INamedList<V> > > ahbsd.lib.NamedCollections.DictionaryOfNamedList< K, V >.OnNamedListAdded
Happenes, if a new INamedList<T> was added.
Referenced by ahbsd.lib.NamedCollections.DictionaryOfNamedList< K, V >.Add().
The documentation for this class was generated from the following file:
ahbsd.lib/NamedCollections/DictionaryOfNamedList.cs