ahbsd.lib.Tools.Checksum Class Reference
Class to calculate checksums.
Static Public Member Functions
static long GetChecksum (long value)
Gets the checksum of the given value.
static short GetFinalChecksum (long value)
Gets the final checksum from a given value.
static ? long GetChecksum (long? value)
Gets the checksum of the given value.
static ? short GetFinalChecksum (long? value)
Gets the final checksum from a given value.
static ulong GetChecksum (ulong value)
Gets the checksum of the given value.
static ushort GetFinalChecksum (ulong value)
Gets the final checksum from a given value.
static ? ulong GetChecksum (ulong? value)
Gets the checksum of the given value.
static ? ushort GetFinalChecksum (ulong? value)
Gets the final checksum from a given value.
static bool IsPositiv (long value)
Checks wheather value is positive or negative.
static bool IsPositive (long? value)
Checks wheather value is positive or negative.
static bool IsPositiv (ulong value)
Checks wheather value is positive or negative.
static bool IsPositive (ulong? value)
Checks wheather value is positive or negative.
static bool IsPositiv (short value)
Checks wheather value is positive or negative.
static bool IsPositive (short? value)
Checks wheather value is positive or negative.
Detailed Description
Class to calculate checksums.
Member Function Documentation
GetChecksum() [1/4]
static long ahbsd.lib.Tools.Checksum.GetChecksum (long value) [static]
Gets the checksum of the given value.
Parameters
value The given value.
Returns
The checksum of the given value.
References ahbsd.lib.Tools.Checksum.IsPositiv().
Referenced by ahbsd.lib.Tools.Checksum.GetChecksum(), and ahbsd.lib.Tools.Checksum.GetFinalChecksum().
GetChecksum() [2/4]
static ? long ahbsd.lib.Tools.Checksum.GetChecksum (long? value) [static]
Gets the checksum of the given value.
Parameters
value The given value.
Returns
The checksum of the given value or null if value is as well null.
References ahbsd.lib.Tools.Checksum.GetChecksum().
GetChecksum() [3/4]
static ulong ahbsd.lib.Tools.Checksum.GetChecksum (ulong value) [static]
Gets the checksum of the given value.
Parameters
value The given value.
Returns
The checksum of the given value.
GetChecksum() [4/4]
static ? ulong ahbsd.lib.Tools.Checksum.GetChecksum (ulong? value) [static]
Gets the checksum of the given value.
Parameters
value The given value.
Returns
The checksum of the given value or null if value is as well null.
References ahbsd.lib.Tools.Checksum.GetChecksum().
GetFinalChecksum() [1/4]
static short ahbsd.lib.Tools.Checksum.GetFinalChecksum (long value) [static]
Gets the final checksum from a given value.
Parameters
value The given value.
Returns
The final checksum of the given value.
References ahbsd.lib.Tools.Checksum.GetChecksum(), and ahbsd.lib.Tools.Checksum.IsPositiv().
GetFinalChecksum() [2/4]
static ? short ahbsd.lib.Tools.Checksum.GetFinalChecksum (long? value) [static]
Gets the final checksum from a given value.
Parameters
value The given value.
Returns
The final checksum of the given value.
References ahbsd.lib.Tools.Checksum.GetChecksum(), and ahbsd.lib.Tools.Checksum.IsPositiv().
GetFinalChecksum() [3/4]
static ushort ahbsd.lib.Tools.Checksum.GetFinalChecksum (ulong value) [static]
Gets the final checksum from a given value.
Parameters
value The given value.
Returns
The final checksum of the given value.
References ahbsd.lib.Tools.Checksum.GetChecksum().
GetFinalChecksum() [4/4]
static ? ushort ahbsd.lib.Tools.Checksum.GetFinalChecksum (ulong? value) [static]
Gets the final checksum from a given value.
Parameters
value The given value.
Returns
The final checksum of the given value.
References ahbsd.lib.Tools.Checksum.GetChecksum().
IsPositiv() [1/3]
static bool ahbsd.lib.Tools.Checksum.IsPositiv (long value) [static]
Checks wheather value is positive or negative.
Parameters
value The value to check.
Returns
true if value is positive, otherwise false.
Referenced by ahbsd.lib.Tools.Checksum.GetChecksum(), ahbsd.lib.Tools.Checksum.GetFinalChecksum(), and ahbsd.lib.Tools.Checksum.IsPositive().
IsPositiv() [2/3]
static bool ahbsd.lib.Tools.Checksum.IsPositiv (short value) [static]
Checks wheather value is positive or negative.
Parameters
value The value to check.
Returns
true if value is positive, otherwise false.
IsPositiv() [3/3]
static bool ahbsd.lib.Tools.Checksum.IsPositiv (ulong value) [static]
Checks wheather value is positive or negative.
Parameters
value The value to check.
Returns
true if value is positive, otherwise false.
IsPositive() [1/3]
static bool ahbsd.lib.Tools.Checksum.IsPositive (long? value) [static]
Checks wheather value is positive or negative.
Parameters
value The value to check.
Returns
true if value is positive, otherwise false.
References ahbsd.lib.Tools.Checksum.IsPositiv().
IsPositive() [2/3]
static bool ahbsd.lib.Tools.Checksum.IsPositive (short? value) [static]
Checks wheather value is positive or negative.
Parameters
value The value to check.
Returns
true if value is positive, otherwise false.
References ahbsd.lib.Tools.Checksum.IsPositiv().
IsPositive() [3/3]
static bool ahbsd.lib.Tools.Checksum.IsPositive (ulong? value) [static]
Checks wheather value is positive or negative.
Parameters
value The value to check.
Returns
true if value is positive, otherwise false.
The documentation for this class was generated from the following file:
ahbsd.lib/Tools/Checksum.cs