ahbsd.lib.Password.Password Class Reference
A Password class.
Public Member Functions
Password ()
Constructor without any parameter.
Password (string passwd)
Constructor with a given password.
Password (IContainer container)
Constructor with a given owning container.
Password (string passwd, IContainer container)
Constructor with a given password and a given owning container.
override bool Equals (object obj)
Compares an other object with this object.
bool Equals (IPassword other)
Compares an other IPassword with this object.
override int GetHashCode ()
Gets the HashCode.
Static Public Member Functions
static ICharacteristicDictionary GetCharasteristics (string value)
Gets the password charasteristics of the given string.
static IPassword GetPassword (string value)
Gets a Password from a given string.
static IPassword GetPassword (string value, IContainer container)
Gets a Password from a given string.
static int GetLowerCases (string value)
Gets the amount of lower cases in the given string.
static int GetUpperCases (string value)
Gets the amount of upper cases in the given string.
static int GetSpaces (string value)
Gets the amount of spaces in the given string.
static int GetNumbers (string value)
Gets the amount of numbers in the given string.
static int GetSpecials (string value)
Gets the amount of special chars in the given string.
static Charasteristic GetCharasteristic (char c)
Gets the Charasteristic of a given char.
static bool operator== (Password left, Password right)
Compares two Passwords.
static bool operator!= (Password left, Password right)
Compares two Passwords.
Properties
string? Value [get, set]
Gets or sets the value.
int Length [get]
Gets the length of the password.
int LowerCases [get]
Gets the amount of lower cases.
int UpperCases [get]
Gets the amount of upper cases.
int Numbers [get]
Gets the amount of numbers.
int Spaces [get]
Gets the amount of spaces.
int Specials [get]
Gets the amount of special cases.
ICharacteristicDictionary Characteristics [get]
Gets the characteristics of a password.
Check.ISecurityValue SecurityValue [get]
Gets the SecurityValue.
Events
ChangeEventHandler< IPassword > OnChange
Happenes, when the Value changes.
Detailed Description
A Password class.
Constructor & Destructor Documentation
Password() [1/4]
ahbsd.lib.Password.Password.Password ()
Constructor without any parameter.
References ahbsd.lib.Password.Password.OnChange.
Referenced by ahbsd.lib.Password.Password.GetPassword(), and ahbsd.lib.Password.Check.SecurityValue.SecurityValue().
Password() [2/4]
ahbsd.lib.Password.Password.Password (string passwd)
Constructor with a given password.
Parameters
passwd The given password.
References ahbsd.lib.Password.Password.OnChange.
Password() [3/4]
ahbsd.lib.Password.Password.Password (IContainer container)
Constructor with a given owning container.
Parameters
container The given owning container.
References ahbsd.lib.Password.Password.OnChange.
Password() [4/4]
ahbsd.lib.Password.Password.Password (string passwd, IContainer container)
Constructor with a given password and a given owning container.
Parameters
passwd The given password.
container The given owning container.
References ahbsd.lib.Password.Password.OnChange.
Member Function Documentation
Equals() [1/2]
bool ahbsd.lib.Password.Password.Equals (IPassword other)
Compares an other IPassword with this object.
Parameters
other The other IPassword.
Returns
true if the other IPassword eaquals this password, otherwise false.
References ahbsd.lib.Password.IPassword.Value, and ahbsd.lib.Password.Password.Value.
Equals() [2/2]
override bool ahbsd.lib.Password.Password.Equals (object obj)
Compares an other object with this object.
Parameters
obj The other object.
Returns
true if the other object eaquals this password, otherwise false.
GetCharasteristic()
static Charasteristic ahbsd.lib.Password.Password.GetCharasteristic (char c) [static]
Gets the Charasteristic of a given char.
Parameters
c The given char.
Returns
The Charasteristic.
Referenced by ahbsd.lib.Password.Password.GetSpecials().
GetCharasteristics()
static ICharacteristicDictionary ahbsd.lib.Password.Password.GetCharasteristics (string value) [static]
Gets the password charasteristics of the given string.
Parameters
value The given string.
Returns
The password charasteristics.
GetHashCode()
override int ahbsd.lib.Password.Password.GetHashCode ()
Gets the HashCode.
Returns
The HashCode.
References ahbsd.lib.Password.Password.Value.
GetLowerCases()
static int ahbsd.lib.Password.Password.GetLowerCases (string value) [static]
Gets the amount of lower cases in the given string.
Parameters
value The given string.
Returns
The amount of lower cases.
GetNumbers()
static int ahbsd.lib.Password.Password.GetNumbers (string value) [static]
Gets the amount of numbers in the given string.
Parameters
value The given string.
Returns
The amount of numbers.
GetPassword() [1/2]
static IPassword ahbsd.lib.Password.Password.GetPassword (string value) [static]
Gets a Password from a given string.
Parameters
value The given string.
Returns
The Password.
References ahbsd.lib.Password.Password.Password().
GetPassword() [2/2]
static IPassword ahbsd.lib.Password.Password.GetPassword (string value, IContainer container) [static]
Gets a Password from a given string.
Parameters
value The given string.
container An owning container.
Returns
The Password.
References ahbsd.lib.Password.Password.Password().
GetSpaces()
static int ahbsd.lib.Password.Password.GetSpaces (string value) [static]
Gets the amount of spaces in the given string.
Parameters
value The given string.
Returns
The amount of spaces.
GetSpecials()
static int ahbsd.lib.Password.Password.GetSpecials (string value) [static]
Gets the amount of special chars in the given string.
Parameters
value The given string.
Returns
The amount of special chars.
References ahbsd.lib.Password.Password.GetCharasteristic().
GetUpperCases()
static int ahbsd.lib.Password.Password.GetUpperCases (string value) [static]
Gets the amount of upper cases in the given string.
Parameters
value The given string.
Returns
The amount of upper cases.
operator!=()
static bool ahbsd.lib.Password.Password.operator!= (Password left, Password right) [static]
Compares two Passwords.
Parameters
left The password on the left side.
right The password on the right side.
Returns
true if both passwords do not eaquals, otherwise false.
operator==()
static bool ahbsd.lib.Password.Password.operator== (Password left, Password right) [static]
Compares two Passwords.
Parameters
left The password on the left side.
right The password on the right side.
Returns
true if both passwords eaquals, otherwise false.
Property Documentation
Characteristics
ICharacteristicDictionary ahbsd.lib.Password.Password.Characteristics [get]
Gets the characteristics of a password.
Length
int ahbsd.lib.Password.Password.Length [get]
Gets the length of the password.
The length of the password.
LowerCases
int ahbsd.lib.Password.Password.LowerCases [get]
Gets the amount of lower cases.
The amount of lower cases.
Numbers
int ahbsd.lib.Password.Password.Numbers [get]
Gets the amount of numbers.
The amount of numbers.
SecurityValue
Check.ISecurityValue ahbsd.lib.Password.Password.SecurityValue [get]
Gets the SecurityValue.
The SecurityValue.
Spaces
int ahbsd.lib.Password.Password.Spaces [get]
Gets the amount of spaces.
The amount of spaces.
Specials
int ahbsd.lib.Password.Password.Specials [get]
Gets the amount of special cases.
The amount of special cases.
UpperCases
int ahbsd.lib.Password.Password.UpperCases [get]
Gets the amount of upper cases.
The amount of upper cases.
Value
string? ahbsd.lib.Password.Password.Value [get], [set]
Gets or sets the value.
The value.
Referenced by ahbsd.lib.Password.Password.Equals(), and ahbsd.lib.Password.Password.GetHashCode().
Event Documentation
OnChange
ChangeEventHandler<IPassword> ahbsd.lib.Password.Password.OnChange
Happenes, when the Value changes.
Referenced by ahbsd.lib.Password.Password.Password().
The documentation for this class was generated from the following file:
ahbsd.lib/Password/Password.cs